version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hr_system
      MYSQL_USER: hr_user
      MYSQL_PASSWORD: hr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hr-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: hr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hr-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr-backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=hr_user
      - DB_PASSWORD=hr_password
      - DB_NAME=hr_system
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - hr-network
    restart: unless-stopped

  # Frontend UI
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: hr-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hr-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  hr-network:
    driver: bridge